### ISSUE TITLE
Данните?

### ISSUE THREAD

**Issue by kberov** [chitanka/sites-rbe-data#1]
Здравейте!
Вършите чудесна работа – полезна за всички! Имам въпрос.
Данните дали се обновяват и как мога да се сдобия с най-новите данни, ако „да“?
Предоставяте ли данните своевременно — dumps — и т.н.?
Съдействате ли си по някакъв начин с БАН?

**Comment by bmanolov** [comment]
В момента няма планове за обновяване на данните и по всяка вероятност този проект ще бъде преустановен.

**Comment by kberov** [comment]
Благодаря за сведенията.
