### ISSUE TITLE
Как се сдобихте с данните?

### ISSUE THREAD

**Issue by Spooghetti420** [chitanka/sites-rbe-data#2]
Здравейте, таман да се опитам някакси да сваля и аз по някакъв начин данните на този речник, и ви намерих тази страница, където може просто да си го изтегля. Проблемът, с който се борих преди е, че трябва човек да реши CAPTCHA на страницата за да прочете дефинициите, така че не можеше с бот да се реши автоматично. Също така, не бих могъл да отгатна всичките думи, коите дори съществуват в речника, защото просто не ги знам всичките. По този начин не можах да измисля начин да събера тези данни – така че, може ли да попитам откъде можахте да ги свалите? Изглежда, че имате директен достъп до базата данни, но аз не можах да намера даунлоуд на rbe. Последно – аз ще използвам HTML файла, но иначе как се четат данните от .sql файловете? Просто искам да ги прехвърля в CSV формат, че този вид ми е по-удобен за използване в Python програми. Изключителен hack, ама за на Читанката данните ползвах regex да аналузирам всичките думи и да си избера елементите, които ми трябваха. Би било много хубаво, ако имаше по-лесен начин за това.
Благодаря за вниманието, и зъжалявам, ако има правописни грешки.

**Comment by bmanolov** [comment]
Преди имаше начин да се свали всичко наведнъж, но вече не е възможно.
