### ISSUE TITLE
Моджибаке?

### ISSUE THREAD

**Issue by Spooghetti420** [chitanka/sites-rbe-data#3]
Току-що видях такъв вид символи, като отворих .html файла:

Îð­íà­ìåí­òà­ëåí ìî­òèâ â æè­ïî­ïèñ­òà, ðú­êî­ïè­ñ­íà­òà óê­ðà­ñà, çëà­òàð­ñ­ò­âî­òî,
äúð­âî­ðåç­áà­òà è äð. âúâ âèä íà ïðå­ï­ëå­òå­íè ãå­î­ìå­ò­ðè­÷­íî è õó­äî­æåñ­ò­âå­íî
ñòè­ëè­çè­ðà­íè ñòå­á­ëà, ëèñ­òà, ãå­î­ìå­ò­ðè­÷­íè ôè­ãó­ðè ñúñ ñèì­âî­ëè­÷­íî
çíà­÷å­íèå, âê­ëþ÷­âà­ùè ïî­íÿ­êî­ãà òåê­ñ­òî­âå ñ àðàá­ñ­êî ïè­ñ­ìî. <i>Ñà­ìà­òà
÷åð­ê­âà å ñú­ùî îá­ðà­çåö íà åê­ñ­öåí­ò­ðè­÷­íîñò. Îò­âúí òÿ å ïðè­ëè­÷­íà íà
òóð­ñ­êà ìå­÷åò è öÿ­ëà å èç­ïè­ñà­íà ñ ðà­ç­íîö­âå­ò­íè àðà­áåñ­êè. </i>Èâ. Âà­çîâ,
Ñú÷. ÕVI, 134. <i>À âñå­êè äîì å òúé îðè­ãè­íà­ëåí è êðà­ñèâ! .. Òîë­êî­âà ðà­ç­ëè­÷­íè
ñòè­ëî­âå.. Îò ÷ó­ä­íè­òå àðà­áåñ­êè íà ìà­â­ðè­òàí­ñ­êèÿ ñòèë äî òåæ­êè­òå ëè­íèè
íà ñêàí­äè­íàâ­ñ­êà­òà êú­ùà. </i>Á. Øè­âà­÷åâ, ÏÞÀ, 163. <i>Àñè­ðî­âà­âè­ëî­íÿ­íè­òå
èç­ïîë­çó­âà­ëè â ñâî­ÿ­òà äå­êî­ðà­öèÿ ñ ãî­ëÿ­ìî ñú­âúð­øåí­ñ­ò­âî è àðà­áåñ­êà­òà</i> 

Абсолютно всички думи изглеждат така, и погледа в браузера изглежда по същия начин. Има ли как да се преведат тези codepointове в правилната форма? Пише в файла, `<meta charset="utf-8">`, но текстът въобще не е такъв според мен.
Edit: всъщност, можах да намеря едно изключение: единствено думата 'ДИАНЕТИКА' е изписана правилно. Освен това, и в SQL базата има някои такива проблеми.

**Comment by bmanolov** [comment]
Навремето и сайта на РБЕ показваше такива боклуци, затова създадохме нашата версия. Възможно е вече да са поправили базата си.

Ето как тези данни бяха поправени навремето: https://github.com/chitanka/sites-rbe/blob/master/app/Service/RbeCleaner.php

Конкретно за горния пасаж първо трябва да се направи конвертиране от utf-8 към windows-1252, а след това от windows-1251 към utf-8.

**Comment by Spooghetti420** [comment]
Благодаря, с тези инструкции ще мога да се оправя. Хубав ден.
